### ISSUE TITLE
[MSVC] error not found gf_undelete

### ISSUE THREAD

**Issue by Voskrese** [getfem-doc/getfem#1]
v5.3 libgetfemint.vcxproj
..\..\interface\src\gf_undelete.cc

v4.3 found gf_undelete ?

pls update proj msvc

delete in proj str libgetfemint.vcxproj
..\..\interface\src\gf_undelete.cc

error
```
e:\tools\vcpkg\buildtrees\getfem\x64-windows-rel\80b20d7c43-beee2414f8\src\getfem_contact_and_friction_nodal.cc(183): error C2039: 'delaunay': is not a member of 'getfem' [E:\tools\vcpkg\buildtrees\getfem\x64-windows-rel\80b20d7c43-beee2414f8\msvc\libgetfem\libgetfem.vcxproj]
  e:\tools\vcpkg\buildtrees\getfem\x64-windows-rel\80b20d7c43-beee2414f8\src\getfem_contact_and_friction_nodal.cc(31): note: see declaration of 'getfem'
e:\tools\vcpkg\buildtrees\getfem\x64-windows-rel\80b20d7c43-beee2414f8\src\getfem_contact_and_friction_nodal.cc(183): error C3861: 'delaunay': identifier not found [E:\tools\vcpkg\buildtrees\getfem\x64-windows-rel\80b20d7c43-beee2414f8\msvc\libgetfem\libgetfem.vcxproj]
```

c1xx : fatal error C1083: Cannot open source file: '..\..\src\getfem_generic_assembly.cc': No such file or directory

**Comment by tkoyama010** [comment]
Hi, Thank you for your issue.
・ This is a mirror repository for getfem document translation. So could you use the official [repository](https://git.savannah.nongnu.org/git/getfem.git
) by reading the [document](http://getfem.org/project/contribute.html)?
・ Compiling by Visual Studio is not supported officially as far as I know. Could you compile in command line by reading this document?
- [Linux](http://getfem.org/install/install_linux.html)
- [windows](http://getfem.org/install/install_windows.html)
- [mac](http://getfem.org/install/install_mac.html) ?

**Comment by tkoyama010** [comment]
If you want to have official support you can contact in [mailing list](https://lists.nongnu.org/mailman/listinfo/getfem-commits)

**Comment by Voskrese** [comment]
see the mscv directory on the git version of GetFEM++ for some MSCV project files

git clone https://git.savannah.nongnu.org/git/getfem.git

mistakes are the same as now

**Comment by tkoyama010** [comment]
Thanks. I will report it.
