### ISSUE TITLE
3d XFEM crack example files 

### ISSUE THREAD

**Issue by kevinxiaomu** [getfem-doc/getfem#35]
Hi, i am trying to use getfem++ for some 3D crack analysis. do you know where can i find simiilar example files?

There are some screenshots on the website, but it seems no 3D crack example files can be found.

**Comment by tkoyama010** [comment]
@kevinxiaomu Thank you for your question. Sorry I don't know about 3D crack analysis examples. You maybe get answer if you email to user support mailing list getfem-users[at-mark]nongnu.org . (This is a mirror repository of getfem and other developer don't see issue.) Thank you for reading.
